spring.application.name=5g-security-ids

# Port du serveur (8080 par défaut, on peut le garder)
server.port=8080

# --- Connexion MongoDB ---
# On se connecte au MongoDB de free5GC qui est exposé sur le port 27017 par Docker
# Si ta DB a un mot de passe (ce n'est pas le cas par défaut sur free5gc-compose), ajoute-le ici.
spring.data.mongodb.uri=mongodb://localhost:27017/free5gc_ids_db

# (Optionnel) Pour voir les logs détaillés de Spring
logging.level.org.springframework.web=INFO